### ISSUE TITLE
Induction forge and electric forge not heating up items

### ISSUE THREAD

**Issue by wormzjl** [DrFair/TFCEngineer#3]
They consumes power, but not heating up stuff

**Comment by wormzjl** [comment]
Probably because I'm using the modified version from technodefirmacraft

**Comment by DrFair** [comment]
I remember Technodefirmacraft having a specific custom mod that makes all items not in specific inventories cool down much quicker. To fix this, you have to increase the heating rate multiplier in TFC Engineer configs. 
I did some testing and it seems like increasing the multiplier by 10, so default 12 for electric forge and 13 for induction forge, will counteract the cool down rate.
This is not TFC that does this by default means and I could make a check for it, but since it only happens with this custom mod only available through this pack, I will not.
Thanks for the report!

**Comment by wormzjl** [comment]
This is weird...After the update I cannot put ores inside the electric forge, and with the following config I still can 't get things to heat up
    S:electricForgeHeatRate=12.0
    S:inductionForgeHeatRate=13.0
Still investigating……

Ok seem that I just need a bigger value, but is it intended that this thing cannot smelt ores?

**Comment by DrFair** [comment]
Yes, it is only supposed to heat up items that can be heated up to work with and so on (excluding food).
Since ores doesn't actually have a heat value, you still need a crucible or something else to smelt them.
